version: "3"

services:
    auth:
        image: rdelorier/php:7.1-fpm-alpine
        volumes:
            - ./auth:/var/www/sso.example.com
        working_dir: /var/www/sso.example.com
        environment:
            - APP_NAME=Auth Example
            - APP_ENV=local
            - APP_KEY=base64:9QNnM8RHpX57xRDX7RFyAd17rtOtVhiV2/8FQ2h5YRI=
            - APP_DEBUG=true
            - APP_LOG_LEVEL=debug
            - APP_URL=http://sso.example.com
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_USERNAME=root
            - DB_PASSWORD=secret
            - DB_DATABASE=sso
            - REDIS_HOST=redis
            - MAIL_DRIVER=smtp
            - MAIL_HOST=smtp.mailtrap.io
            - MAIL_PORT=2525
            - MAIL_USERNAME=8b3bf8d7a4015b
            - MAIL_PASSWORD=dc96fff6f3c437
    
    application:
        image: rdelorier/php:7.1-fpm-alpine
        working_dir: /var/www/application.example.com
        volumes:
            - ./application:/var/www/application.example.com

    redis:
        image: redis

    mysql:
        image: mariadb
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=sso

    web:
        image: openresty/openresty:trusty
        ports:
            - 80:80
            - 443:433
        volumes:
            - ./auth:/var/www/sso.example.com
            - ./application:/var/www/application.example.com
            - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./access.lua:/access.lua